on:
    push:
        branches: deploy/vercel
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.3'

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Install Dependencies
              run: composer install

            - name: Migrate DB
              run: |
                php artisan migrate --force --seed
                #php artisan storage:link
              env:
                APP_ENV: production
                DB_CONNECTION: sqlite
                # DB_HOST: ${{ secrets.DB_HOST }}
                # DB_PORT: 3306
                # DB_DATABASE: ${{ secrets.DB_DATABASE }}
                # DB_USERNAME: ${{ secrets.DB_USERNAME }}
                # DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                # MYSQL_ATTR_SSL_CA: /etc/ssl/certs/ca-certificates.crt


            - name: Deploy to Vercel
              run: vercel deploy --prod --token=e9VPd1ztmE8L61OCsSk6JJ5Y
              env:
                VERCEL_ORG_ID: team_9NN245EkWKW9CPvAkSFn4OfY
                VERCEL_PROJECT_ID: prj_KmGGjZpmU5un6PjbpEuRB7tNy3Yd
